# Generated by Django 3.2.5 on 2021-07-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='vegetarienne',
            field=models.BooleanField(default=False),
        ),
    ]
